server:
  port: 8080

spring:
  application:
    name: wisercat-be-demo
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/filter}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: database/liquibase-changeLog.xml
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/filter}
    driver-class-name: org.postgresql.Driver
    user: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
