server:
  port: 8081

spring:
  application:
    name: wisercat-be-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    driver-class-name: org.postgresql.Driver
    username: 'admin'
    password: 'admin'
