server:
  port: 8081

spring:
  application:
    name: wisercat-be-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/filter
    username: 'admin'
    password: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
